using UnityEngine;

namespace IndianOceanAssets.Engine2_5D
{
    /// <summary>
    /// 敌人出生点标记 —— 挂到场景中的空物体上，标记敌人出生位置。
    /// EnemyManager 会在游戏开始时找到所有出生点并生成敌人。
    ///
    /// 用法：在场景中放置空物体，挂上此组件，调整位置即可。
    /// Scene 视图中显示红色线框球 + 竖线，方便辨认。
    /// </summary>
    public class EnemySpawnPoint : MonoBehaviour
    {
        [Tooltip("Gizmo 球体半径（仅编辑器可视化）")]
        [SerializeField] private float gizmoRadius = 0.5f;

        private void OnDrawGizmos()
        {
            Gizmos.color = Color.red;
            Gizmos.DrawWireSphere(transform.position, gizmoRadius);
            Gizmos.DrawLine(transform.position, transform.position + Vector3.up * 2f);
        }
    }
}
